services:
- docker
install:
- echo "Iniciando Instalacão :)!"
# Script que carrega configuração de Variaveis AWS
script:
- echo "Inicando Build e Push para o ECR!"
- sh "./ecr_credentials.sh"
after_success:
# Validacão versão do docker
- docker --version
# Depois de validação de versão, é instalado o pacote aws-cli
- pip install --user awscli
# Comandos ECR para autenticação em repositório, processo de tag, build e push realizados realizados do modo padrão.
- aws ecr create-repository --repository-name guilhermerenew/python-app --image-tag-mutability IMMUTABLE --region eu-west-3
- aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 417311404467.dkr.ecr.eu-west-3.amazonaws.com
- docker build -t guilhermerenew/python-app .
- docker tag guilhermerenew/python-app:latest 417311404467.dkr.ecr.eu-west-3.amazonaws.com/guilhermerenew/python-app:latest
- docker push 417311404467.dkr.ecr.eu-west-3.amazonaws.com/guilhermerenew/python-app:latest
# Lista de imagens ativas em repositório!
- aws ecr describe-images --repository-name guilhermerenew/python-app --region eu-west-3
# Variaveis de Ambiente AWS encriptografadas! 
env:
  global:
  - secure: g50oDO0wyUT8/ZM8xwGWCQ6U2lKLwd4DQgtDTN7K/YkfM5UjgnXVLV4dMwKnHelGKXIVII2DqbN8ur7T+fHgdwwx4TyZ0K1Gg4JPRNe/jAz+8x2xZV2nHtofDtvE9K7M0vI+oeua8r152lXlq54BeB72eq5hwuDHUITeAQ+Y3YHIkX9jnDH7SzlAmPRbcH0nZm0fy+wrrTyjVdapweP/fJkeceSNC6apK6pDfs/xErFo4lzHkiC20hRzySkr1kIw6aY8KGg7B7DewRl7h7/hLbmoLTclTFEZffNckS3zQE4UNDVqdPnwkK8+C7R+b8I/j+IOdmcSgCB87b97ERQJ8LtP1QtWuaI5hcqjl04i0zCqx2A8ta4MhiVrLlBD9efafxgF6BZRkH/PEOJ0BsfhnuMohN79zrGPF7Z/r31LMgbZhbjzJP5KIuuGimabdZQgatD5PVEBIx+ENWKfQObQYA43qdHm0Law4HOM3/lD0/8+XNmgKx7fL+jKFzO15TqF3jPvi+g0kTwGDvfRhDBtXTKp19atJNjlp8gVZOPQ0S+E+bOXdZU+70xnSp2LxtR4Ma87/RWdqNeIfKfE1w0Vc7ct0Bb6G3Dab0FqhybgusYKOotdzvV+I9gACC7qiE9llixRT4sq2vpI1eqEPfNzmxgBmQ3DCRUZ0XefAmqWwws=
  - secure: EVPA9PSMCEyZSt6z4XYcmLC+2bEYJeL6/aFCzjtdX2vUrClozNScA6bMlhcXQfy7w7Wu27Tuo0tAYvsYRdz5BGoClkZyD6L+k3s/LJWPFe96ePuLubQk3qSLEk4GV2Zt7+qvlVxhE1nw7by94J8ceOdbV4DHYuX2dc0Y+Os9mRs4d96dkfVvIo4E4UZSvlT5lEyGGTKfMMxxqxupqjTFryq2GZTGBZZ0Z4M/ta7bQaeE8bmF4jpzGe49wSrEra2+icd0aDqrHwDhZ+Xn8C70dGNNI5WcF6bWuUG8up8ZS2VuqkrKBCnM2feA8Q+FYixLZJzGbVftnogIdsblY9Jk1HJDIU3VvdVCeBNhdNLaWTkR+I8SUQx3w1zs1C88nRKiXyXoAj3nos82xhvvpU6m+GQ3P8foxvyYd5gycG+7N1xFBDgm8wMaMc0YtbIgWeVpg0QOWPUzC/ARNdluJHf9X2JHRDS32HF0CP9BRkO9et3QPHEfe8aqoYFeRh+H89GnHmU4bG+iyL/Ec/O7OMJfIaUkUAeLZsOLjX6x7tMjh/ZzdNDxYNv/ox006ZG74aUmqCU4drrroTExriUK2w2jwuJCIzGCH6fkHPUac99zoBhEUUdDlEtLBxJ8o4N3wFxSL9UUEtiqtXAx2uqjRcFfxiUegEVidBOp0rW7LYwSvPE=
# Slack Webhook Notification 
notifications:
  slack:
    secure: f6MoDC3ebj//VWe2Oiwisrf36wDEshII4Bdg47DePgOtKMqiyJ+t4mvCUv7vglyJhrvs+kUvuhmMZClSFGcNGEkSpHXVMliwVuWcK6D3PljTfnSDoCFnr6XcumNtFV4ZrUdAIqtu2/aEY5YyasO3g0oVMQyX+oyd1f3Zu4jxTTO6uPgPh9HACbxnmVEWcmXbyWnTiuyRJPDdZKtnYAdDh5+kyraRn6CHe8p4YBhuxKyQl6TWHHP/Se0sxgOlElxVedasCtsmNo4FvZIGsc3xr5xwxrtTEEuy9AxCXMAEbm5q6x7O73kl4DJqgdPloO5nXixI9DEG8SGcf9zlJd+W3tO/hfMbm9T5VfXFxBFQh0KgAW+c6KwA1oPaoqvQhGBTGEZwf3760pMQ77VckQUS72JsZKvhtu2iWQd/Fu2AgLyGf7BNeQkoHbfx10p5zOdBMMobfj2z2AazY6Jgsk58JAtWG0SMZjOfbNcFDStnflU+fI/zATjwn0wmJxW4DDV1z1SphQkgnaBLYO03Z7aUo0WN26J91kAwEEliUQ/erp3eoZ0oJRrBa5jkri4CJreEz4MdkdrVcFEH3wM23awpp0Mwwa4tID7pADezqE3L1H6kKArWUBRL2KxS4iUP0/2VuoDBb5GfLK2N1AjIkBaYNTW6D71sYn9q0acx/9uUFyk=