services:
  - docker
install:
  - echo "Iniciando Instalacão :)!"
# Script que carrega configuração de Variaveis AWS
script:
  - echo "Inicando Build e Push para o ECR!"
  - sh "./setup-pipeline-steps/ecr_credentials.sh"
after_success:
# Validacão versão do docker
  - docker --version
# Depois de validação de versão, é instalado o pacote aws-cli
  - pip install --user awscli
# Comandos ECR para autenticação em repositório, processo de tag, build e push realizados realizados do modo padrão.
  - aws ecr create-repository --repository-name guilhermerenew/python-app --image-tag-mutability IMMUTABLE --region eu-west-3
  - aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 417311404467.dkr.ecr.eu-west-3.amazonaws.com
  - docker build -t guilhermerenew/python-app .
  - docker tag guilhermerenew/python-app:latest 417311404467.dkr.ecr.eu-west-3.amazonaws.com/guilhermerenew/python-app:latest
  - docker push 417311404467.dkr.ecr.eu-west-3.amazonaws.com/guilhermerenew/python-app:latest
# Lista de imagens ativas em repositório!
  - aws ecr describe-images --repository-name guilhermerenew/python-app --region eu-west-3
# Inicia uma vm type xenial instalando o pacote terraform.

dist: xenial
language: bash
# Instalacao terraform package
before_install:
  - wget https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip
  - unzip terraform_0.12.25_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_0.12.25_linux_amd64.zip
jobs:
  include:
# Passo 1 - Terraform Plan
  - stage: terraform plan deployment
    if: type IN (pull_request)
    script:
    - terraform init -backend-config backend_config/dev.tfvars
    - terraform plan
# Passo 2 - Terraform Apply
  - stage: terraform destroy deployment 
    script:
    - terraform init
    - terraform plan
    - terraform validate
    - terraform apply -auto-approve
# Auto Merge caso status de pipeline seja success TDLR
    after_success: ./setup-pipeline-steps/merge.sh $USERNAME $PASSWORD

# Variaveis de Ambiente AWS encriptografadas! 
env:
  global:
  - secure: g50oDO0wyUT8/ZM8xwGWCQ6U2lKLwd4DQgtDTN7K/YkfM5UjgnXVLV4dMwKnHelGKXIVII2DqbN8ur7T+fHgdwwx4TyZ0K1Gg4JPRNe/jAz+8x2xZV2nHtofDtvE9K7M0vI+oeua8r152lXlq54BeB72eq5hwuDHUITeAQ+Y3YHIkX9jnDH7SzlAmPRbcH0nZm0fy+wrrTyjVdapweP/fJkeceSNC6apK6pDfs/xErFo4lzHkiC20hRzySkr1kIw6aY8KGg7B7DewRl7h7/hLbmoLTclTFEZffNckS3zQE4UNDVqdPnwkK8+C7R+b8I/j+IOdmcSgCB87b97ERQJ8LtP1QtWuaI5hcqjl04i0zCqx2A8ta4MhiVrLlBD9efafxgF6BZRkH/PEOJ0BsfhnuMohN79zrGPF7Z/r31LMgbZhbjzJP5KIuuGimabdZQgatD5PVEBIx+ENWKfQObQYA43qdHm0Law4HOM3/lD0/8+XNmgKx7fL+jKFzO15TqF3jPvi+g0kTwGDvfRhDBtXTKp19atJNjlp8gVZOPQ0S+E+bOXdZU+70xnSp2LxtR4Ma87/RWdqNeIfKfE1w0Vc7ct0Bb6G3Dab0FqhybgusYKOotdzvV+I9gACC7qiE9llixRT4sq2vpI1eqEPfNzmxgBmQ3DCRUZ0XefAmqWwws=
  - secure: EVPA9PSMCEyZSt6z4XYcmLC+2bEYJeL6/aFCzjtdX2vUrClozNScA6bMlhcXQfy7w7Wu27Tuo0tAYvsYRdz5BGoClkZyD6L+k3s/LJWPFe96ePuLubQk3qSLEk4GV2Zt7+qvlVxhE1nw7by94J8ceOdbV4DHYuX2dc0Y+Os9mRs4d96dkfVvIo4E4UZSvlT5lEyGGTKfMMxxqxupqjTFryq2GZTGBZZ0Z4M/ta7bQaeE8bmF4jpzGe49wSrEra2+icd0aDqrHwDhZ+Xn8C70dGNNI5WcF6bWuUG8up8ZS2VuqkrKBCnM2feA8Q+FYixLZJzGbVftnogIdsblY9Jk1HJDIU3VvdVCeBNhdNLaWTkR+I8SUQx3w1zs1C88nRKiXyXoAj3nos82xhvvpU6m+GQ3P8foxvyYd5gycG+7N1xFBDgm8wMaMc0YtbIgWeVpg0QOWPUzC/ARNdluJHf9X2JHRDS32HF0CP9BRkO9et3QPHEfe8aqoYFeRh+H89GnHmU4bG+iyL/Ec/O7OMJfIaUkUAeLZsOLjX6x7tMjh/ZzdNDxYNv/ox006ZG74aUmqCU4drrroTExriUK2w2jwuJCIzGCH6fkHPUac99zoBhEUUdDlEtLBxJ8o4N3wFxSL9UUEtiqtXAx2uqjRcFfxiUegEVidBOp0rW7LYwSvPE=
  - secure: V0QqNe2UmDxJx2E1S3PozFR+WgOdYQ2HwUWLsUgQYnV0EcwBkMeqfzAvZuf384KRVMAvX57jE/csBAfgB9ce3UpwspeOpzAXJz89RifRASJzJfTwt7wPg0yReuOCTW/5IotcVoyYPOMxyQ5lC1L1EWsYBkVDD1vs7SJtrZgkO+KGzFNsATR2E0r3H2IH3TZu91j4tW4oVlmEMdXxl6nO7UHQjo6xKZjAg6j4YO44f0dfGyoNOka/YJyhYTBUDgabyToHi69dhBMUSKDKG9BB4WW4K8NZYXgFPLDye8rtr8m+HrvQivWytH5lOK7OEQ/s276gGUf8hhzSijQQpFPKGA77KQPNk0cWQQc3Tsdggtf7le1U1XT1apX3cah2r3Yadqm+X4/8N0M6NqEUGa7o8L/h0oYGiaEU98GAg1A8gAV4X3+JMLXWOQjBJ1FUHd6EgaM5lJExS4a4akVqUO2Cl5Tg3DZ+MkVvTU3+kJ8j4X3z5EQ3pKRsIe4VLnjK0fE2jbpSWZtxnrKOjV/4XTL+BZbGWY/8PkgohcHUOCsFDS3aLYb9f/Jh039Vwp1srsh2Xs+CpylWRu91ZejT3RVU63zWOHAlKdu2RdObfu08H96J5/Y5aaOlm5LWTamDcxG/GTg9eEwuGYk8D0cvcRcrjCQmbYeOUXbNmCP49OSI8DM=
  - secure: IAYZ45y8RgDX52rS6buo/wqM+gDxekQcezPqv6nSmtEYdxaNucoZeMqiC+5E8Rky9fepaEWH4ALaIJOlN4PVeD2D2jyzbGGMQn2dauB3BAZP+JnCbg08T70uZqRzXTPPrPRPLJ6ChH774vhoPl01cg6jgbELpR5Bu1pQ/GBgc7e/fB42ucSQ1Cv2bMfx5bBnxlR1kY6soaI/uYEzOza54Q9g/t49aFRIMYSHI8x1EXVCLTt/D2PtKDL01HiQUJ2vBty0YjSZ1vn55x3s2jrzlh6O9vABHd/D1+3iGFBnEoRNsDHNPHS3FV+04TpKB5thECVj4SO9rbcnL9AF7MMmgbck41pU3jQPKcAWV6SjffO5kQksWlYCHK/5OB+JzMSXv9RF0GpDnDq/Cm12rZihYyiI41TZKrNzziHEZHzwcDj+PFcCZttGfjjgFMchOwCoDJJIDxwABtzU+v6jfcKkzAeC3D2xi+lJeKp+IK9bgphOkNLEgjX0OV8YENZLRKyQFu+vwc3cU2vAy2Wo1zo4EWZ3d+m4+RZOUUYq7ndMmsNNUtREMg6/qrYyaBvBcEFT7EoXLKoCkNzBwzmgFTLYn5bgG2rt8DKUBu0z11cNGgHbcIJvH3iNFP324O7K74naQ5xEG3GizwvnoAzrt6Uwqid2TmuY59CgAaIkWKAObd0=
# Slack Webhook Notification 
notifications:
  slack: testing-webhookers:6tsCRhdSZknC8053HgXMAbNH